# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='EUR',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
