# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_article_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='CHF',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='GBP',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='RON',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='RUB',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='UAH',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='USD',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
