# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20170216_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='UAH',
            new_name='CNY',
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
