# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20170223_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_date',
        ),
    ]
