# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_remove_article_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='UAH',
            new_name='CNY',
        ),
    ]
