# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20170223_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='CNY',
            new_name='UAH',
        ),
    ]
