# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='CHF',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='EUR',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='GBP',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='RON',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='RUB',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='UAH',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='USD',
            field=models.CharField(max_length=500),
        ),
    ]
