# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20170311_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
