# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='CNY',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='CHF',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='EUR',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='GBP',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='RON',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='RUB',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='UAH',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='USD',
            field=models.TextField(),
        ),
    ]
