# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20170318_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='UAH',
        ),
        migrations.AlterField(
            model_name='article',
            name='CNY',
            field=models.TextField(),
        ),
    ]
