# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20170319_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
