# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='About us', max_length=10),
        ),
    ]
