# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_auto_20171016_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICOname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICO_name', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('info_block', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('ICO_image', models.ImageField(blank=True, upload_to='new')),
            ],
        ),
    ]
