# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-27 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_iconame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconame',
            name='rate',
        ),
    ]
